version: '3.9'

services:
  db:
    container_name: postgres_container
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ontibike
    ports:
      - 5432:5432
    volumes:
      - pgVolFinal:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - practica_net
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    container_name: pgadmin4_container_final
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadminFinal:/var/lib/pgadmin
    networks:
      - practica_net
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"
    networks:
      - practica_net
  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend_container
    ports:
      - 5173:5173
    command: npm run dev
    networks:
      - practica_net

volumes:
  pgVolFinal: {}
  pgadminFinal: {}

networks:
  practica_net: