# Generated by Django 5.0.1 on 2024-02-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_station', to='stations.station')),
                ('exit_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_station', to='stations.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.train')),
            ],
        ),
    ]
